In [1]:
import numpy as np

# Take matrix order
n = int(input("Enter the order of the matrix (e.g., 2 for 2x2): "))

# Create an empty list
matrix = []

print("\nEnter the matrix elements:")

# Take matrix input
for i in range(n):
    row = []
    for j in range(n):
        value = int(input(f"Element [{i+1}][{j+1}] : "))
        row.append(value)
    matrix.append(row)

# Convert list into NumPy array
arr = np.array(matrix)

# Find diagonal sum using loop
diagonal_sum = 0
for i in range(n):
    diagonal_sum += arr[i][i]

# Display matrix
print("\nMatrix:")
print(arr)

# Display diagonal sum
print("\nSum of diagonal elements =", diagonal_sum)

Enter the order of the matrix (e.g., 2 for 2x2): 3

Enter the matrix elements:
Element [1][1] : 2
Element [1][2] : 4
Element [1][3] : 3
Element [2][1] : 3
Element [2][2] : 6
Element [2][3] : 4
Element [3][1] : 6
Element [3][2] : 8
Element [3][3] : 9

Matrix:
[[2 4 3]
 [3 6 4]
 [6 8 9]]

Sum of diagonal elements = 17
